meta_product_name: "JobJob"
meta_title: "JobJob - Keep track of all your job applications in one place"
meta_description: "JobJob is a tool that helps you keep track of all your job applications. Add tasks, notes and documents to each job and change the application status as you progress in your job search."
meta_image: "cover.jpg"