meta_product_name: "JobJob"
meta_title: "JobJob - Keep track of all your job applications in one place"
meta_description: "JobJob is a tool that helps you keep track of all your job applications. You can add tasks, notes and documents to each job and track the status of your application."
meta_image: "cover.jpg"